# Generated by Django 3.2.10 on 2021-12-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Demo',
            },
        ),
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name_plural': 'Advert'},
        ),
    ]
