# Generated by Django 3.2.10 on 2021-12-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211227_0544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
