# Generated by Django 3.2.10 on 2021-12-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
        ('blog', '0008_auto_20211227_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.advert'),
        ),
    ]
