# Generated by Django 3.2.10 on 2021-12-27 11:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
        ('blog', '0009_blogindexpage_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSnippetAdverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.advert')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_placements', to='blog.blogindexpage')),
            ],
            options={
                'verbose_name': 'advert placement',
                'verbose_name_plural': 'advert placements',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
