# Generated by Django 3.2.10 on 2021-12-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=255, verbose_name='标题')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
