# Generated by Django 3.2.10 on 2022-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
