# Generated by Django 3.2.10 on 2022-01-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
