# Generated by Django 3.2.10 on 2022-01-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_banner_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '轮播图资源'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='banner_title',
            new_name='title',
        ),
    ]
