# Generated by Django 3.2.10 on 2022-01-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('snippets', '0006_auto_20220107_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='元数据标题')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': '元数据资源',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
