# Generated by Django 3.2.10 on 2022-01-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20220107_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='type',
        ),
    ]
