# Generated by Django 3.2.10 on 2022-01-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_remove_metadata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
