# Generated by Django 3.2.10 on 2022-01-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_metadata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
