# Generated by Django 3.2.10 on 2022-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_alter_metadata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('A', 'A')], max_length=20),
        ),
    ]
