# Generated by Django 3.2.10 on 2022-01-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('snippets', '0011_alter_metadata_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='请输入Banner标题', max_length=30, verbose_name='Banner标题')),
            ],
        ),
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.ForeignKey(help_text='请选择元数据对应的图片资源', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(help_text='请输入元素数据标题', max_length=255, verbose_name='元数据标题'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('MOBILE', '移动无线端版本'), ('PC', '电脑端版本')], help_text='请选择元数据适用平台', max_length=20),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='url',
            field=models.URLField(help_text='请输入元数据跳转链接'),
        ),
        migrations.CreateModel(
            name='BannerToMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner_meta', to='snippets.banner')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.metadata')),
            ],
        ),
    ]
