# Generated by Django 3.2.10 on 2022-01-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_auto_20220108_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='fifth',
            field=models.ForeignKey(blank=True, help_text='请选择第五张轮播图元素数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AddField(
            model_name='banner',
            name='first',
            field=models.ForeignKey(help_text='请选择第一张轮播图元素数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AddField(
            model_name='banner',
            name='fouth',
            field=models.ForeignKey(blank=True, help_text='请选择第四张轮播图元素数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AddField(
            model_name='banner',
            name='second',
            field=models.ForeignKey(blank=True, help_text='请选择第二张轮播图元素数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AddField(
            model_name='banner',
            name='sixth',
            field=models.ForeignKey(blank=True, help_text='请选择第六张轮播图元素数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AddField(
            model_name='banner',
            name='third',
            field=models.ForeignKey(blank=True, help_text='请选择第三张轮播图元素数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.DeleteModel(
            name='BannerToMeta',
        ),
    ]
