# Generated by Django 3.2.10 on 2022-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_auto_20220108_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('MOBILE', '移动无线端版本'), ('PC', '电脑端版本')], default='PC', help_text='请选择元数据适用平台', max_length=20),
        ),
    ]
