# Generated by Django 3.2.10 on 2022-01-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('snippets', '0014_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='img_url',
            field=models.URLField(blank=True, help_text='请输入图片url地址', verbose_name='远程图片资源URL'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.ForeignKey(blank=True, help_text='请选择元数据对应的图片资源', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='本地图片资源'),
        ),
    ]
