# Generated by Django 3.2.10 on 2022-01-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_auto_20220108_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=255)),
                ('icp_license', models.CharField(max_length=255)),
                ('police_license', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='fifth',
            field=models.ForeignKey(blank=True, help_text='请选择第五个元数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='first',
            field=models.ForeignKey(help_text='请选择第一个元数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='fouth',
            field=models.ForeignKey(blank=True, help_text='请选择第四个元数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='second',
            field=models.ForeignKey(blank=True, help_text='请选择第二个元数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sixth',
            field=models.ForeignKey(blank=True, help_text='请选择第六个元数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='third',
            field=models.ForeignKey(blank=True, help_text='请选择第三个元数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='请输入元数据集合标题', max_length=30, verbose_name='元数据集合标题'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('MOBILE', '移动无线端版本'), ('PC', '电脑端版本'), ('ALL', '适用所有平台')], default='PC', help_text='请选择元数据适用平台', max_length=20),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('MOBILE', '移动无线端版本'), ('PC', '电脑端版本'), ('ALL', '适用所有平台')], help_text='请选择元数据适用平台', max_length=20),
        ),
    ]
