# Generated by Django 3.2.10 on 2022-01-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_auto_20220111_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='fouth',
            new_name='fourth',
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='请输入导航栏名称')),
                ('fifth', models.ForeignKey(default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner')),
                ('first', models.ForeignKey(default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner')),
                ('fourth', models.ForeignKey(default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner')),
                ('second', models.ForeignKey(default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner')),
                ('third', models.ForeignKey(default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner')),
            ],
        ),
    ]
