# Generated by Django 3.2.10 on 2022-01-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_auto_20220112_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '元数据集合'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name_plural': '元数据'},
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'verbose_name_plural': '导航栏（Nav）'},
        ),
        migrations.AlterField(
            model_name='nav',
            name='fifth',
            field=models.ForeignKey(blank=True, default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='first',
            field=models.ForeignKey(blank=True, default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='fourth',
            field=models.ForeignKey(blank=True, default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='second',
            field=models.ForeignKey(blank=True, default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='third',
            field=models.ForeignKey(blank=True, default=None, help_text='请选择第一个导航菜单', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='snippets.banner'),
        ),
    ]
