# Generated by Django 3.2.10 on 2022-01-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0021_metadata_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='label',
        ),
    ]
