# Generated by Django 3.2.10 on 2022-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0022_remove_metadata_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='label',
            field=models.CharField(blank=True, help_text='请输入元数据展示标题', max_length=50, verbose_name='展示标题'),
        ),
    ]
