# Generated by Django 3.2.10 on 2022-01-12 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('snippets', '0023_metadata_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.ForeignKey(blank=True, help_text='请选择元数据对应的图片资源', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='本地图片资源'),
        ),
    ]
