# Generated by Django 3.2.10 on 2022-06-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0024_alter_metadata_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='MetadataList',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
