# Generated by Django 3.2.10 on 2022-07-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0025_auto_20220613_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': '页脚'},
        ),
    ]
