# Generated by Django 3.2.10 on 2022-01-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20220107_0940'),
        ('home', '0004_homebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='type',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='url',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.metadata'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata'),
        ),
    ]
