# Generated by Django 3.2.10 on 2022-01-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20220107_0940'),
        ('home', '0005_auto_20220107_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name_plural': 'HomeBanner'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.metadata', verbose_name='请选择元数据'),
        ),
    ]
