# Generated by Django 3.2.10 on 2022-01-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220107_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['sort_order']},
        ),
    ]
