# Generated by Django 3.2.10 on 2022-01-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_auto_20220108_1247'),
        ('home', '0007_alter_homebanner_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='metadata',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.banner', verbose_name='请选择Banner'),
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
    ]
