# Generated by Django 3.2.10 on 2022-01-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0024_alter_metadata_image'),
        ('home', '0008_auto_20220108_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nav',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.nav', verbose_name='请选择导航'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.banner', verbose_name='请选择轮播图'),
        ),
    ]
