# Generated by Django 3.2.10 on 2023-08-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220112_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '主页模板'},
        ),
    ]
