# Generated by Django 3.2.10 on 2023-08-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '主页模板', 'verbose_name_plural': '主页模板-----更多'},
        ),
    ]
